[package]
authors = ["rep-nop <repnop@outlook.com>"]
name = "bismite"
version = "0.1.0"
[dependencies]
codespan = "0.1.1"
codespan-reporting = "0.1.3"
isomorphism = "0.1.2"
lazy_static = "1.0.0"
structopt = "0.2.7"
structopt-derive = "0.2.7"
