[package]
authors = ["rep-nop <repnop@outlook.com>"]
name = "bismite"
version = "0.1.0"

[dependencies]
codespan = "0.2.0"
codespan-reporting = "0.2.0"
isomorphism = "0.1.2"
lazy_static = "1.2.0"
structopt = "0.2.13"
